version: "2.2"
networks:
  helionogueir-tips-javascript:
    driver: bridge
services:
  helionogueir-tips-javascript-workspace:
    cpus: 2
    mem_limit: 112m
    image: node:12-slim
    container_name: helionogueir-tips-javascript-workspace
    working_dir: /root/workspace
    environment:
      - NODE_ENV=development
    networks:
      - helionogueir-tips-javascript
    volumes:
      - ./src:/root/workspace
    tty: true